### ISSUE TITLE
Litra Beam: brightness range not properly mapped

### ISSUE THREAD

**Issue by bernhardvogler** [timrogers/litra#132]
Hi,

First of all: the package is really cool!

Here's an issue I'm facing: using Logitech's own G Hub software, I can get my Litra Bream to shine much brighter than when I'm using this package's CLI. While I can control the brightness of my Litra Beam with both `litra-brightness` and `litra-brightness-lm`, in both cases the maximum supported number does not correspond to the maximum brightness of the device.
It seems that the maximum brightness value is not mapped properly.

My setup:
- Litra Beam
- MacBook Air M1 2020 with macOS 13.2.1 (22D68)
- `npm view litra version` -> `4.4.0`

Please let me know which other information I could provide to help debug this.

**Comment by timrogers** [comment]
Very interesting! I don't have a Beam, so it's a bit hard for me to test. I will try this with my Glow on G-a hub to rule out a wider problem, and then get back to you.

**Comment by bernhardvogler** [comment]
Thanks for the swift response!
I've been debugging a little this afternoon, but I'm a noob when it comes to USB and I haven't coded much for years. However, I believe I found the reason: the bug seems to be that in `setBrightnessInLumen` the `integerToBytes` conversion is missing (which you have for the color temperature). With the Beam, the lumen range exceeds 255 and so you get an overflow. I changed the code in the JS file locally and it works!
But given that I'm a noob I don't feel like opening a PR …

**Comment by timrogers** [comment]
@bernhardvogler Thanks again for looking into this and figuring out the issue. Would you be able to give my code change in #135 a try?

**Comment by bernhardvogler** [comment]
I can confirm that after fetching the branch and checking out `timrogers/fix-132` running `node litra-brightness-lm.js 400` in `dist/commonjs/cli` works as expected. Also, the percentage-based brightness settings are now working. 🎉
Thanks a lot for maintaining the library!
