### ISSUE TITLE
Explain how to update in README

### ISSUE THREAD

**Issue by bernhardvogler** [timrogers/litra#138]
A suggestion:
Maybe it's just me, still sharing it here. I was struggling to update the package to get https://github.com/timrogers/litra/pull/135 (thanks again for the fix!) after having initially installed it using `npm install -g litra`. I tried `npm update -g litra` but that didn't change the files that were linked in my PATH. I ended up manually removing the files in `/usr/local/lib/node_modules/` and reinstalling the litra package with `npm install -g litra`. Maybe you could add a sentence on how to update the latest version to the README? (Or maybe it was just a weird thing with my system's setup, I don't know …)

I'm on macOS 13.2.1 and had installed node.js using `brew`.

**Comment by timrogers** [comment]
👋 Sorry to hear you had challenges upgrading! That does sound like something setup specific as Node should know that it needs to replace the scripts in your path. I'd be really interested to know if an uninstall and reinstall would work for you.

**Comment by bernhardvogler** [comment]
I ended up `rm`'ing the litra files that were in my PATH and did a fresh install with `npm install -g litra` and that did the trick!
