### ISSUE TITLE
litra-oversight breaks with OverSight 2.1.8

### ISSUE THREAD

**Issue by jbelkins** [timrogers/litra#259]
I am using `litra@4.4.3`.

OverSight 2.1.8 adds a new command line argument:  `-activeCount`
When this new arg is passed into `litra-oversight` it fails:
```
error: unknown option '-activeCount'
```

**Comment by timrogers** [comment]
Fixed in v4.4.4: https://github.com/timrogers/litra/releases/tag/v4.4.4
