### ISSUE TITLE
Does not work with Logitech Litra Beam LX

### ISSUE THREAD

**Issue by jbsparrow** [timrogers/litra#288]
I see that the code does not have support for the Litra Beam LX. I tried connecting to it by adding it to the driver file but the HID values are incorrect so all readings from it are wrong. I do not have any experience with brute forcing HID codes. Could someone who has experience with bruteforcing HID values help me out?

**Comment by jbsparrow** [comment]
Thank you! I tested it and it works perfect! I'm not sure how the changes affect support for the other litra products and am unable to test it. Hopefully the changes can be merged with no issues.

Your wrapper is definitely better than any of the others I've seen so far :)

**Comment by timrogers** [comment]
@jbsparrow That's great news! I'll take a look at this over the next few days and will add Beam LX support to this package for the basic features - would you be willing to test it once I have some working code? 😊

**Comment by jbsparrow** [comment]
I would be glad to test it!

**Comment by lnovelli** [comment]
Hi @timrogers and @jbsparrow ! Thank you for creating this extremely helpful wrapper and I'm glad to see that my (quite dirty 😅) fork is helping, I created it in a rush for a Hackathon 🙈 Unfortunately I think that my changes might break compatibility with the standard Litra Beam/Glow as I had to change a couple of HID bytes in almost every function to make it work on the Beam LX. Let me know if that's the case and if I can be of any help! Best

**Comment by timrogers** [comment]
> Hi @timrogers and @jbsparrow ! Thank you for creating this extremely helpful wrapper and I'm glad to see that my (quite dirty 😅) fork is helping, I created it in a rush for a Hackathon 🙈 Unfortunately I think that my changes might break compatibility with the standard Litra Beam/Glow as I had to change a couple of HID bytes in almost every function to make it work on the Beam LX. Let me know if that's the case and if I can be of any help! Best

No worries at all - your fork had the all-important research on the HID bytes, and I've written this PR to send the right bytes based on the device ☺️ Thank you for figuring out the hard bits!
