### ISSUE TITLE
Is there a way to get current settings?

### ISSUE THREAD

**Issue by christi-stripe** [timrogers/litra#42]
My end goal is to map a button on my keyboard to toggle my light on and off. I don't see a way in the library to get a device's current status/settings. The only way I can see to do this is to leave a script running which listens for events and keeps track of if the light is on or off, which I bet will be flaky. I was also looking into the HID library you're using and don't see an obvious way there.

**Comment by timrogers** [comment]
:wave: Not too sure on that one I'm afraid! I'm convinced there will be a way to do it, but I haven't figured it out yet.

**Comment by timrogers** [comment]
There's some prior art here that may well be relevant: https://github.com/zource-dev/litra-glow/blob/77cc79313d56814ea4fd183f86768cbf312703bb/src/main/providers/logitech/litra.ts#L47-L64

**Comment by hhaidar** [comment]
Greetings, I just ordered one of these things from Amazon and I was looking to make a toggle button for the Stream Deck 😅 

Check out: https://github.com/kharyam/litra-driver/issues/22#issuecomment-1341525040

I managed to get the device on/off state with something like this:

```
device.hid.write(padRight([0x11, 0xff, 0x04, 0x01], 20, 0x00));

device.hid.read((err, data) => {
  // 1 = on, 0 = off
  if (data[4]) {
    ...
  }
});
```

Getting brightness:

```
device.hid.write(padRight([0x11, 0xff, 0x04, 0x31], 20, 0x00));

device.hid.read((err, data) => {
  // data[5] ranges from 20 to 250 using G Hub
 // data[3] is usually 49, not sure what this represents
  console.info(data[5]);
});
```

For color temp: `device.hid.write(padRight([0x11, 0xff, 0x04, 0x81], 20, 0x00))...`

**Comment by hhaidar** [comment]
Also thank you for writing this library, I can confirm it works on Windows!
