### ISSUE TITLE
Confirm minimum brightness for Litra Beam device

### ISSUE THREAD

**Issue by timrogers** [timrogers/litra#77]
When adding support for the Litra Beam, I assumed that its minimum brightness was 20 Lumens, like the Litra Glow. The maximum is documented on the Logitech website, but not the minimum.

We should double check that and update the constant if required.

https://github.com/timrogers/litra/blob/9b68dc0813fd5439f3ccccb9338e715cbe503364/src/driver.ts#L19

**Comment by timrogers** [comment]
@StevenRudenko Would you be able to take a look at this? The best way, I think, would be to manually see what happens when you set the brightness to different values over and over `20`.

**Comment by StevenRudenko** [comment]
@timrogers the lowest possible value applied on Beam for brightness in lumen is `30`

**Comment by StevenRudenko** [comment]
the maximum value accepted is `767`

**Comment by StevenRudenko** [comment]
if I write Lumen like this, I get more brightness

`device.hid.write(padRight([0x11, 0xff, 0x04, 0x4c, **0x01**, brightnessInLumen], 20, 0x00));`

**Comment by timrogers** [comment]
@StevenRudenko That's really interesting - surprising that you can go for a higher brightness than the one documented by Logitech! 

I'll correct the minimum value in the code. What do you think about values beyond the documented maximum? Perhaps we could default to enforcing the minimum and maximum, but allow people to turn off those validations? We will also have to change the byte generation.

**Comment by StevenRudenko** [comment]
> @StevenRudenko That's really interesting - surprising that you can go for a higher brightness than the one documented by Logitech!
> 
> I'll correct the minimum value in the code. What do you think about values beyond the documented maximum? Perhaps we could default to enforcing the minimum and maximum, but allow people to turn off those validations? We will also have to change the byte generation.

I like an idea with override limits, just in case firmware will be changed

**Comment by StevenRudenko** [comment]
> if I write Lumen like this, I get more brightness
> 
> `device.hid.write(padRight([0x11, 0xff, 0x04, 0x4c, **0x01**, brightnessInLumen], 20, 0x00));` seems the value could be more than fits into one byte

Logitech GHub can go the same high brightness as I do if I set the second byte. So it is available for Beam officially. @timrogers could you please suggest how to capture UBS messages sent by G Hub?

**Comment by timrogers** [comment]
> @timrogers could you please suggest how to capture UBS messages sent by G Hub?

I'm not sure I'm afraid 😦 

> Logitech GHub can go the same high brightness as I do if I set the second byte.

Do you know how to construct the byte array? Or is that what you're trying to work out by capturing GHub messages?

**Comment by StevenRudenko** [comment]
> 
> Do you know how to construct the byte array? Or is that what you're trying to work out by capturing GHub messages?

maybe we can try to do same as it is done for the temperature
`https://github.com/timrogers/litra/blob/main/src/driver.ts#L116` will check it late the week

**Comment by timrogers** [comment]
@StevenRudenko Thanks!

**Comment by StevenRudenko** [comment]
@timrogers I've captured the USB messages the official app does to Litra Beam for lights:
for minimum brightness it sends `11ff044b**001e**0000000000000000000000000000`
for maximum brightness it is `11ff044b**0190**0000000000000000000000000000`

also I've found out that the fourth byte is random after each device connection, meaning the message prefix is always `11ff04` than the random byte then the command

**Comment by timrogers** [comment]
Thanks! Sounds like our current limits are correct.
