### ISSUE TITLE
Setting temperature as a percentage does not work for all values

### ISSUE THREAD

**Issue by timrogers** [timrogers/litra#92]
Setting your Litra's temperature to a percentage value using the `litra-temperature` CLI or the `setTemperaturePercentage` function does not work reliably.

Based on my testing, it seems that you cannot make set the temperature to _any_ value within your device's supported range. At least from what I'm seeing, it looks like only steps of 100 are supported. The brightness-related features work as expected.

I'd love to have someone else test this to see if it's something specifically wrong with my device. If it isn't, then we can figure out a way forward - either removing the percentage functionality for temperature or "snapping" to the allowed values.

## Reproduction steps

_Note that the allowed temperature range for a Litra Glow is 2700-6500K_

1. Set your Litra Glow's temperature to 0% by running `litra-temperature 0`. You observe a change in the light.
2. Set your Litra Glow's temperature to 10% by running `litra-temperature 10`. Nothing happens.
3. Set your Litra Glow's temperature to 100% by running `litra-temperature 100`. You observe a change in the light.
4. Set your Litra Glow's temperature to 2700K by running `litra-temperature-k 2700`. You observe a change in the light.
5. Set your Litra Glow's temperature to 2799K by running `litra-temperature-k 2799`. Nothing happens.
6. Set your Litra Glow's temperature to 2800K by running `litra-temperature-k 2800`. You observe a (small!) change in the light.

**Comment by timrogers** [comment]
@StevenRudenko @leggetter Would either of you have a few minutes to give this a try for me, just to confirm that I am not going mad? 😓

**Comment by NMichas** [comment]
I confirm, it is as @timrogers mentioned, you can only use steps of 100. In my scripts, I adjust it as: 
```
if (temperature !== Math.round(temperature/100)*100) {
   temperature = Math.round(temperature/100)*100
   console.log("Temperature rounded to " + temperature);
}
```
